### ISSUE TITLE
ESP882 D not defined issue

### ISSUE THREAD

**Issue by wilkinsonaw11** [Jaycar-Electronics/WiFi-Relay-Controller#1]
Hi, I have been trying to get the Jaycar electronice wifi relay controller project happening, When i'm uploading the program for the WiFi i keep getting a fault 

D was not declared in this scope

with this line highlighted

D("Created soft AP called")

Im a bit of a beginner so any help would be appreciated 
Im hoping to adapt this for use in elevator controls for disabled people
kind regards

**Comment by Jaycar-Electronics** [comment]
have a look near the top of of the file. 

you should see the below code:

```cpp
//another define bunch
//similar to the uno code
//#define D(...) Serial.println(__VA_ARGS__);
//#define D(...)

```

you want to uncomment the #define D(...) so that line just reads like this:

```cpp
#define D(...)
```

**Comment by Jaycar-Electronics** [comment]
I have now made this by default, so you can simply re-download the project and it will have the correct change.

https://github.com/Jaycar-Electronics/WiFi-Relay-Controller/commit/ec70709e04459c7abd0b46609a6529c740afe58b
